/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "on-secondary-fixed-variant": "#00513e",
              "secondary-container": "#a0f3d4",
              "primary-fixed-dim": "#cebdff",
              "surface-variant": "#e8ddff",
              "surface-container-low": "#f8f1ff",
              "surface-container-high": "#eee4ff",
              "on-primary-fixed-variant": "#4f319d",
              "primary-container": "#6b4fbb",
              "outline": "#7a7583",
              "inverse-on-surface": "#f5eeff",
              "primary": "#5335a1",
              "on-surface-variant": "#494552",
              "on-secondary": "#ffffff",
              "surface-tint": "#674bb7",
              "primary-fixed": "#e8ddff",
              "tertiary-fixed-dim": "#ffb873",
              "tertiary-fixed": "#ffdcbf",
              "on-error": "#ffffff",
              "error-container": "#ffdad6",
              "tertiary": "#703f00",
              "inverse-surface": "#342b4e",
              "surface-container-lowest": "#ffffff",
              "on-tertiary-container": "#ffd8b6",
              "surface-bright": "#fdf7ff",
              "secondary-fixed-dim": "#84d6b9",
              "on-tertiary-fixed": "#2d1600",
              "surface-dim": "#e1d3ff",
              "outline-variant": "#cac4d4",
              "on-primary": "#ffffff",
              "surface": "#fdf7ff",
              "on-surface": "#1f1637",
              "on-tertiary-fixed-variant": "#6a3b00",
              "on-primary-fixed": "#21005e",
              "on-primary-container": "#e5d9ff",
              "on-background": "#1f1637",
              "secondary": "#086b53",
              "secondary-fixed": "#a0f3d4",
              "on-tertiary": "#ffffff",
              "error": "#ba1a1a",
              "background": "#fdf7ff",
              "on-secondary-container": "#167159",
              "on-secondary-fixed": "#002117",
              "inverse-primary": "#cebdff",
              "surface-container-highest": "#e8ddff",
              "tertiary-container": "#90540b",
              "surface-container": "#f3eaff",
              "on-error-container": "#93000a"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "xs": "8px",
              "base": "4px",
              "gutter": "24px",
              "sm": "16px",
              "container-max": "1200px",
              "md": "24px",
              "lg": "40px",
              "xl": "64px",
              "margin-mobile": "16px"
      },
      "fontFamily": {
              "display-lg": ["Literata", "serif"],
              "label-caps": ["Inter", "sans-serif"],
              "data-code": ["JetBrains Mono", "monospace"],
              "body-sm": ["Inter", "sans-serif"],
              "headline-md": ["Literata", "serif"],
              "body-lg": ["Inter", "sans-serif"],
              "display-sm": ["Literata", "serif"],
              "body-md": ["Inter", "sans-serif"]
      },
      "fontSize": {
              "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
              "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
              "data-code": ["13px", { "lineHeight": "18px", "letterSpacing": "-0.01em", "fontWeight": "400" }],
              "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
              "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
              "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
              "display-sm": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
              "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
